##### This is a roadmap of the code necessary to replicate the analysis of GCSP data.
#     MCMC model fitting time varies across models.
#     For a quicker overview of the code, I suggest dramatically shortening the sample size in each
#     of the three model fitting scripts from 5000.  Run times for the 5000-sample models
#     are indicated below.

# Note on naming: model names changed during manuscript writing.  The following are equivalent:
#     Manuscript   Code
#     ----------   ----
#       IJ Model = "State Model"... reflecting each animal's perceptibility state
#                = "Survey Model"
#       PP Model = "Event Model"... reflecting the perception of cue events
#       IJ+PP Model = "Combined Model"
# The original nomenclature has propagated widely throughout our code.  Our apologies in
#   advance for any confusion!

### Outputs
#   Reorganized data from Amundson et al. (2018)
#     gcspdata.rds
#   MCMC samples from model fitting (class = 'stanfit'):
#     gcsp_state.rds -- IJ model
#     gcsp_event.rds -- PP model
#     gcspfit.rds    -- IJ+PP model
#   Model summaries generated by ExtractFits.R
#     Outputs.rds
#   Figures generated by CodeToGeneratePlots.R
#     DistByTime.png -- Figure 3 from manuscript
#     Estimates.pdf  -- Figure 4 from manuscript
#     DistByTime.png -- Figure S-5 from Web Supplement


### Load libraries
library(plyr)
library(tidyverse)
library(rstan)
library(mcmcse)
library(ggpubr)


# Set working directory to folder where all of the GCSP analysis code has been extracted (with
#   'StanModels' as a subdirectory)
setwd("<<YOUR PATH>>")


### Order in which to run code

# Helper scripts
source("Scripts.R")                 # Loads helper scripts

# Code to load data.
# The end output of the following two scripts is included in the Supplemental Materials
#   as 'gcspdata.rds' (but will be overwritten by OrganizeData.R)
source("Code from Amundson.R")      # Uses minimally altered Amundson et al. (2018) code to process
                                    #   GCSP data.
source("OrganizeData.R")            # Reorganize data as an input for models

# Model fitting.  MCMC sampling times were 0.6, 2.3, and 27 hours respectively for IJ, 
#   PP, and IJ+PP models.
# If you wish to simply 'test drive' the code, we recommend changing the values of iter in each of the 
#   following from 5000 to 100.  Even then, the IJ+PP model takes a little while.
# Stan model code should be placed in a subdirectory called 'StanModels'

source("Event_Code.R")              # Fit PP model    (uses "inits.rds" as input)
source("State_Code.R")              # Fit IJ model    (uses Stan defaults to initialize MCMC sampling)
source("ApproxCombined_Code.R")     # Fit IJ+PP model (uses "inits_IJPP.rds" as input)

# Compile model fit summary objects for analysis and plotting
source("ExtractFits.R")

# Generate GCSP figures in manuscript
source("CodeToGeneratePlots.R")
